volumes:
  db:
  node_modules:

services:
  backend:
    build:
      context: ./services/backend
      target: builder

    stop_signal: SIGINT
    ports:
      - '8000:8000'
    depends_on:
      - db
  frontend:
    build:
      context: ./services/frontend
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    restart: always
    develop:
      watch:
        - action: sync
          path: ./services/frontend
          target: /usr/src/data_tool
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
