const HomePage = () =>  
(
    <div className="container app-container">
    <h1>This is the Home Page</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum non eros nec faucibus. Proin sollicitudin turpis suscipit orci placerat auctor. Integer sit amet tellus ultrices, hendrerit lacus ut, finibus sapien. Nunc ultricies dolor a sodales venenatis. Integer porttitor, enim sit amet sagittis viverra, risus massa pulvinar neque, a pretium turpis ante eu neque. Cras interdum nunc in hendrerit porttitor. Nam varius rutrum diam ac facilisis. Nulla quis finibus orci, eget dignissim libero. Etiam at sapien ut dolor consectetur maximus faucibus nec erat. Curabitur eget nibh volutpat, rhoncus ante eu, gravida lectus. Maecenas a suscipit libero. Etiam faucibus nulla et nisi auctor, sed ultrices ex consectetur. Morbi ut dui purus. Etiam nec accumsan nisi. Morbi finibus interdum magna, sit amet viverra dolor aliquam id.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin volutpat commodo vulputate. Quisque pulvinar felis nec dolor rutrum pretium. Mauris ac nisl sit amet orci tincidunt luctus non ac est. Proin eu sollicitudin mauris. Donec tempus venenatis libero, et lacinia sem condimentum a. Mauris ut ullamcorper odio. In eros sem, vehicula sit amet lorem vel, accumsan posuere orci. Proin hendrerit, metus nec pellentesque finibus, lacus lectus pulvinar elit, nec porttitor dui nunc eu nunc. Vivamus accumsan laoreet dolor vel blandit.</p>
        <p>Phasellus at odio a sem fringilla bibendum. Nullam ut imperdiet mi. Nunc aliquam quam vitae dolor feugiat, eu consectetur augue pulvinar. Nunc ullamcorper nulla ornare aliquet convallis. Aliquam aliquet erat non aliquam aliquet. Mauris a diam id felis viverra accumsan vel eu arcu. Nullam eu suscipit magna. Sed vel lobortis mauris, a luctus sem. Mauris suscipit sit amet tortor eget feugiat.</p>
        <p>In faucibus pretium justo, id commodo velit porttitor nec. Nullam luctus mi sed suscipit scelerisque. Aliquam diam nulla, posuere eu lobortis sed, lacinia non lorem. Maecenas efficitur lectus ultrices tortor cursus suscipit. Suspendisse ut hendrerit mauris. Maecenas rhoncus augue id arcu venenatis eleifend. Ut eget lorem cursus, dapibus arcu id, dictum libero. Suspendisse eget mi nec nisi ullamcorper vehicula. Mauris hendrerit nisl ut ligula molestie, ut fringilla magna tincidunt. Cras vulputate massa sit amet dapibus efficitur. Cras condimentum congue felis, ac mattis libero semper eu. Donec facilisis nibh felis, quis tincidunt nisi tincidunt sed. Pellentesque vestibulum volutpat risus eget iaculis. Vivamus nec varius odio. Vivamus nec leo lacus.</p>
        <p>Suspendisse in orci vitae lacus cursus rhoncus. Fusce auctor magna in est sollicitudin, et iaculis urna eleifend. Nam sodales lorem porta, mattis metus eu, consequat mauris. Cras tempor lacus quis nunc aliquet aliquam. Aenean non nisi lobortis, dictum libero quis, dapibus lorem. Suspendisse nulla metus, tincidunt eget fringilla a, tempus at metus. Curabitur finibus nulla eget luctus tincidunt. Curabitur eget molestie lectus. Sed porta tellus eu nunc pretium, vitae ultrices dolor aliquam. Fusce ullamcorper ipsum ut augue efficitur ornare. Donec velit leo, tempor non lacus at, tempus fermentum diam. Cras porta varius nisl id egestas. Donec auctor dui a leo scelerisque pharetra. Cras convallis, nisi tempor finibus iaculis, lacus orci aliquet diam, blandit hendrerit dui velit quis arcu. Proin venenatis ante vel ligula cursus ultricies.</p>
    </div>
)


export default HomePage;